# Generated by Django 3.2.8 on 2022-03-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255, verbose_name='Category Title')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=355, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=355, verbose_name='Telegram Name')),
                ('phone_number', models.CharField(max_length=355, verbose_name='Phone Number')),
                ('username', models.CharField(max_length=355, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('total_votes_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.title'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_votes',
            field=models.ManyToManyField(blank=True, to='vote_app.TelegramUser'),
        ),
    ]
