# Generated by Django 3.2.8 on 2022-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_auto_20220315_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='all_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='total_votes_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
