# Generated by Django 4.0.1 on 2022-03-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Kategoriya nomi')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistredBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(verbose_name="Telegram telefo'n no'mer")),
                ('userid', models.PositiveIntegerField(verbose_name='Telegram user id')),
                ('username', models.CharField(max_length=200, verbose_name='Telegram username')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Joy nomi')),
                ('vote', models.PositiveIntegerField(default=0, verbose_name='Bu joyga ovoz berish')),
                ('date', models.DateField(auto_now_add=True)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
            ],
            options={
                'ordering': ['-vote'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.PositiveIntegerField(verbose_name="Telegram telefo'n no'mer")),
                ('userid', models.IntegerField(verbose_name='Telegram user id')),
                ('username', models.CharField(max_length=200, verbose_name='Telegram username')),
                ('name', models.CharField(max_length=200, verbose_name='Telegram user ismi')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
                ('voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.places')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
