# Generated by Django 4.0.1 on 2022-03-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registredbotuser',
            name='date',
        ),
    ]
