# Generated by Django 4.0.1 on 2022-03-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_registredbotuser_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='date',
        ),
    ]
