# Generated by Django 4.0.1 on 2022-03-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_botuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registredbotuser',
            name='allowed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='registredbotuser',
            name='checked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
