# Generated by Django 4.0.1 on 2022-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_imgwrod'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AddField(
            model_name='registredbotuser',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
    ]
